### ISSUE TITLE
AppData description is not displayed correctly

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.electrum.electrum#1]
The description section from AppData doesn't seem to be displayed correctly. See the following screenshot:
![features](https://user-images.githubusercontent.com/2339930/62821977-71704500-bb7d-11e9-83dc-8e09e5aebab9.png)

The only suspicious thing from `appstream-util validate` is:
```
• style-invalid         : <p> is too short [Main features are:]
```

**Comment by A6GibKm** [comment]
Fixed in #3
