### ISSUE TITLE
AppData screenshot has bad quality

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.electrum.electrum#2]
The Electrum screenshot from AppData is blurry and low quality. Please, consider providing a better screenshot, for example [this one](https://jonny.fedorapeople.org/electrum-2.7.12-screenshot-gnome/06-main-empty.png) from Fedora.

**Comment by A6GibKm** [comment]
I was looking for a better screenshot, thanks

**Comment by A6GibKm** [comment]
I implemented it at #3
