### ISSUE TITLE
need to update to 4.3.2

### ISSUE THREAD

**Issue by jontyms** [flathub/org.electrum.electrum#45]

**Comment by A6GibKm** [comment]
Thanks a lot for the reminder, Ill try to update it during the week. Its kind of a slow process as I cannot do local builds of electrum (its the only flatpak where I run out of memory),

**Comment by jontyms** [comment]
Thanks,
I was trying to figure out how to update the flatpak but couldn't figure it out

**Comment by A6GibKm** [comment]
Check the related MR. There was an issue with the new linter that had to be fixed.
