### ISSUE TITLE
Flatpak metainfo outdated

### ISSUE THREAD

**Issue by xmready** [flathub/org.electrum.electrum#47]
The current version of Electrum on Flathub is one version behind

Current version `4.3.2`

Flathub version `4.3.1`

**Comment by A6GibKm** [comment]
We are using 4.3.2. I just forgot to update the [metainfo](https://github.com/flathub/org.electrum.electrum/blob/master/org.electrum.electrum.metainfo.xml), PRs are welcome.

**Comment by xmready** [comment]
> We are using 4.3.2. I just forgot to update the [metainfo](https://github.com/flathub/org.electrum.electrum/blob/master/org.electrum.electrum.metainfo.xml), PRs are welcome.

pull request submitted
