### ISSUE TITLE
update to 4.4.1

### ISSUE THREAD

**Issue by storopoli** [flathub/org.electrum.electrum#49]
Could we please have a new release based on https://github.com/spesmilo/electrum/releases/tag/4.4.1 which was released today?

**Comment by A6GibKm** [comment]
https://download.electrum.org/4.4.1 returns a 404, but ill try to do 4.4.0 today.

**Comment by A6GibKm** [comment]
Could you please test https://github.com/flathub/org.electrum.electrum/pull/50 once CI finishes (should be around 20mins maybe)? Bumping to 4.4.1 should be easy once they have a stable link up.
