### ISSUE TITLE
Add trezor support 

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.electrum.electrum#6]
See https://github.com/spesmilo/electrum/issues/5017

**Comment by yanchenko-igor** [comment]
I created a fork and I build the master branch there https://github.com/yanchenko-igor/org.electrum.electrum

**Comment by A6GibKm** [comment]
I don't know why but it won't build cython for me. If your build compiles make a PR so the bot makes a build.

**Comment by A6GibKm** [comment]
Change electrum source to
```json
                {
                    "type": "git",
                    "url": "https://github.com/spesmilo/electrum.git",
                    "commit": "f52072e1693107b07e29e4d3a68ee944f1020381"
                },
```
I managed to build it after a restart. I think this is fine.

**Comment by A6GibKm** [comment]
Added in #7. Thanks @yanchenko-igor .
